server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name _;
    root /var/www/muvautomation;
    index index.html;

    # Ocultar tokens del servidor
    server_tokens off;
    client_max_body_size 100k;

    # Cabeceras de Seguridad Avanzadas
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-Frame-Options "DENY" always;
    add_header Referrer-Policy "no-referrer" always;
    add_header Content-Security-Policy "default-src 'self' 'unsafe-inline'; object-src 'none';" always;
    add_header X-XSS-Protection "1; mode=block" always;

    # Bloqueo de Métodos HTTP no permitidos
    if ($request_method !~ ^(GET|HEAD|POST)$ ) {
        return 405;
    }

    # Bloqueo de escáneres automáticos de vulnerabilidades por User-Agent
    if ($http_user_agent ~* (sqlmap|nikto|gobuster|dirb|wpscan|masscan|acunetix|nessus) ) {
        return 403;
    }

    # Deshabilitar listado de directorios
    autoindex off;

    # Bloquear acceso a archivos ocultos y sensibles (.git, .env, .bak, .conf, .sql)
    location ~ /(\.|\.env|\.bak|\.conf|\.sql|\.py|\.sh|\.exe) {
        deny all;
        access_log off;
        log_not_found off;
    }

    location / {
        try_files $uri $uri/ =404;
    }
}
